# Rust formatting configuration

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"

# Imports
imports_indent = "Block"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments
comment_width = 80
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Strings
format_strings = false
format_macro_matchers = true
format_macro_bodies = true

# Functions and methods
fn_single_line = false
where_single_line = false
force_explicit_abi = true
use_field_init_shorthand = true
force_multiline_blocks = false

# Control flow
control_brace_style = "AlwaysSameLine"
trailing_comma = "Vertical"
trailing_semicolon = false
match_block_trailing_comma = true

# Spaces
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"

# Miscellaneous
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
remove_nested_parens = true
combine_control_expr = false
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
use_try_shorthand = true
condense_wildcard_suffixes = false

# Stability
unstable_features = false